# WhatATheme
markdown: kramdown

# URL of the Site
url: 'jonasb.at'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Portfolio
# Description of the Site
description: Projects created by Jonas Bodingbauer
# URL of Image of the Site
site-image: 
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo.png

front-video: /assets/videos/FrontVideo.webm

front-image: /assets/images/FlipdotClock.jpg
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email:
facebook_username: 
twitter_username: Caesiumhydroxid
instagram_username: 
linkedin_username: 
github_username:  
youtube_channel_id: UCx-6y_BPJhfca3HvH6zWxVw
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Jonas Bodingbauer
# URL for the Image of the Author
author-image: /assets/images/ProfilePicture.JPG
# 60 Words About the Author
author-about: I consider myself a<a href="https://en.wikipedia.org/wiki/Maker_culture">Maker</a>. I am passionate about electronics, informatics and<a href="https://en.wikipedia.org/wiki/STEAM_fields">STEAM</a>. When I find time to work on projects I love to build things out of old technologies - trying to put new life into them by combining them with new technology. Currently, I am studying Electrical Engineering as well as Software Engineering at<a href="https://www.tuwien.at/">TU Wien</a>.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: 

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-compress-images

# Compress Images
compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,JPG,jpeg,svg}"

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _compress_images_cache.yml
